language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: cloudwheels-dev

env:
  - VUE_APP_TENDERDASH_EXPLORER_SECURE=TRUE
  - VUE_APP_TENDERDASH_EXPLORER_HOST=rpc.cloudwheels.net
  - VUE_APP_TENDERDASH_EXPLORER_PORT=26657